### ISSUE TITLE
eslint and eslint-output find different errors

### ISSUE THREAD

**Issue by strass** [lwhiteley/eslint-output#7]
My standard eslint (`"lint": "eslint src/**/*.ts src/**/*.tsx",`) and my eslint-output `"lint:ci": "eslint-output"` are finding very different errors. I have a `.eslintrc.js` file in the same directory as my `.eslintoutputrc`. I've also tried specifying `.eslintrc.js` in `cliEngineConfig.configFile`.

**Comment by ticky** [comment]
I believe this is because of this piece of unexpected configuration:

https://github.com/lwhiteley/eslint-output/blob/b096c24806c24f8e6eb2c7ab14cf380ab66062be/app.js#L19

`eslint-output` is _overriding_ the env specified by your `.eslintrc`

I have found a workaround of setting an empty `envs` in `cliEngineConfig`:

```json
{
  "files": ["."],
  "cliEngineConfig": {
    "envs": []
  }
}
```

**Comment by lwhiteley** [comment]
release v2.0.1

which removes explicitly setting the env property

**Comment by ticky** [comment]
Thanks for the prompt fix @lwhiteley. Are there any potentially-breaking changes in 2.x?

**Comment by lwhiteley** [comment]
not really. 
removing the envs array may be a behaviour change for others that did not have the same issues so released as a major change, however, everything else remains the same.

it is noted on the readme: https://github.com/lwhiteley/eslint-output#breaking-changes
